language: python
python:
- '2.7'
- '3.6'
os:
- linux
branches:
  except:
  - legacy
  - experimental
  - develop
  - tensorflow
  - features/*

cache: pip
before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda config --set anaconda_upload no
install:
- bash travis_install.sh
script:
- coverage run travis_tests.py
after_success:
- codecov
deploy:
- provider: pypi
  user: fdtomasi
  password:
    secure: Wvo0RfNjtW3CikjE0gVNkP2gH1mf8qrh/5TCkxrAlqUVN0GnRV76JwKE8C55AH0OrpKBSdWEKb54K1OwtwtWlHojrWdKaJG7R3ASprOv6nVn0sBgSH7qmI6DWnKEQlCb0slr3RP2dOdMSuz3rr0rjEppwViSNvLbigZz6IltiG6uDHnMxgfgTWTGV4uamnOQuuZ6PktRzqOW3Rqp4HQNP2+nIvuPwfe06hll45mGHhzyTJC/rSJmV0/bAfr1mo6cFSO7VD/Lmo1Opu1tTl/8FkGVUbCZtTyCasf/F5IB1v8yNy+Tb2HtnOxR6NbnjJkT/vuftOrMFxQPd8ZWVbbeMO3RRlDUR2al5mNK4nI38efgS54ZZIzkx3ek4duAeCm5fwi/FrL+hndtiiT0DNHbQ2QA+b7o/4Ag9kJgcI5M0jYO7rPPg1sgm4nQ4QEugfR0vY5/pSLQSRZ2EY7AKyJsgPc7pkl/t310v0HtEsbmEzEgwOw0SIcc0+bUou53R9E5h1M1xKcLVV9jqyjTs+GahcRd54xMRGsYpDn+9u7i07kj2GqrYjubzvZeL2QSrPMBtujeeKLMQMWAQZ/TmIyLD0f+zh0xpAUb0EYVIEml3a5p2q/kavPVZJAY202Wa7SbJGDVt+02+dgsUJg0nAEvO3xu9JOyY12WkR6QNnQC0Qk=
  distributions: sdist bdist_wheel
  on:
    repo: fdtomasi/regain
    tags: true
    python: '2.7'
- provider: releases
  api_key:
    secure: "iQG9e/v02CbVHD9T4guu9s5Yw37ltKIXb354iHNvyiojXvb4WPywnt9xESoFxeh98fHPVkVBlfDsivGoayao1r2FJO4D4VvVe2RvxXKAupz7qQwX822hfc16dx+UVQ9u5XwhZA9TRJY9aZ3b2Rzu5WkYH9tPDxS/qCue7xTLq6WEjqIq21jK8b9UpjcIOuCQrDuLcozij16S2O+7bLgrGWbTS60R9RtkoDmTAvyET5jmBZAgWSGlApWo5N3QbZQkHY9KELoadgQ4+sEm4A10bAm7hRwcKd2IUgDJvRNPXwGahr5LRdeX8MJMnonVL0QkNrJoxtnUif1WxnMa9eoMn+0xZ7hjHSFp0uE7Ow4E0NyCL7a4zJwiOX3XGDDRsF2iPmhQMwyudutjwEofQgal1ltUHvrxZzx25swY5e6pGvogWhEx6N5VYR8/8qQAd3XCx0bslK2gB9nH+iCeN0oAOXXI3Y6f4gPb3PSGgRkjI3UhzQz3TiAYtDrGQWYhEoVLv17vaoTzsX08RD7yYRNENqXF3iLBPuARxmsEx5PnWL1EU2I9MPT4TTHaYEEOdrkzKJIr6/nAsFH48hrZomYhzJJViBrIDRtYR8B6tB/diMEokC/R49Jb1zgHOsBwC0IKQQlQICdW3hCYmZUK5EKq7wdVvglOiT/kAWkHu/FKe4s="
  skip_cleanup: true
  on:
    repo: fdtomasi/regain
    tags: true
- provider: script
  script: bash deploy_anaconda.sh
  skip_cleanup: true
  on:
    repo: fdtomasi/regain
    tags: true
    password:
      secure: Wvo0RfNjtW3CikjE0gVNkP2gH1mf8qrh/5TCkxrAlqUVN0GnRV76JwKE8C55AH0OrpKBSdWEKb54K1OwtwtWlHojrWdKaJG7R3ASprOv6nVn0sBgSH7qmI6DWnKEQlCb0slr3RP2dOdMSuz3rr0rjEppwViSNvLbigZz6IltiG6uDHnMxgfgTWTGV4uamnOQuuZ6PktRzqOW3Rqp4HQNP2+nIvuPwfe06hll45mGHhzyTJC/rSJmV0/bAfr1mo6cFSO7VD/Lmo1Opu1tTl/8FkGVUbCZtTyCasf/F5IB1v8yNy+Tb2HtnOxR6NbnjJkT/vuftOrMFxQPd8ZWVbbeMO3RRlDUR2al5mNK4nI38efgS54ZZIzkx3ek4duAeCm5fwi/FrL+hndtiiT0DNHbQ2QA+b7o/4Ag9kJgcI5M0jYO7rPPg1sgm4nQ4QEugfR0vY5/pSLQSRZ2EY7AKyJsgPc7pkl/t310v0HtEsbmEzEgwOw0SIcc0+bUou53R9E5h1M1xKcLVV9jqyjTs+GahcRd54xMRGsYpDn+9u7i07kj2GqrYjubzvZeL2QSrPMBtujeeKLMQMWAQZ/TmIyLD0f+zh0xpAUb0EYVIEml3a5p2q/kavPVZJAY202Wa7SbJGDVt+02+dgsUJg0nAEvO3xu9JOyY12WkR6QNnQC0Qk=
notifications:
  slack:
    rooms:
    - secure: rvkrsS1FnFitYBMuc6Y6a6gpN1z+YwFx83M9vsgVFfrng5KS91/veknffWdOF3cVxdZrnB3/xwL8sIr0tsfuKrTs3mVizshhC3KQD3PaE6mgtZ+Ehi2NAYqDNUmU5FHfD6hkIKevrUIuyC5I8qr6dSM6G7gpsaeCfbeM84JK7YTyXsKqTu9vu6rnZU9bQDjD9qAtjVtCaMa1F4edfMittY/QOuPGMXd0KMZAg9qsRvvfT6xKioVwOB0hdCERE5cbR4qrn6j98HHtAGK3z5JVctUHKgST4DWKo8yXJNGv0JSVEaUP0EG1dZ/xst+++8On+SNWKng21c1baXVZJV32mW22zaNRoczvlXVpn5UACHOrZZLQia1HfJf0Lsiiu7192CeDhtgwtOrO5tw94p69l1qLmKjvyqX1owCC6FAXFLG8+/0RvZgir80rMxkty4TlRQCs7M71ZS97CQcOZK6bpiQfFtfltVJFGnsd5As7OMTnleRc2iSnKOu7YJQ6DhjZkFMboJRvvfmHjYYdPdVFrLVMh3A+DriQRHbFb48RtiAZD02kOQtAFn+1niFBye3A8cFdWw5fSWy9HsMCrDtxOPYfduYMY/pdeZd2u2D9gaJm6wCYpa9Tb/WfkvXeamChsoHTGAEUraFnqQ9dTJe1oqyX35HONHqIIVyGCT3X7W4=
    on_success: change
    on_failure: always
  email: false
